services:
  shop-api:
    platform: linux/amd64
    image: cosmtrek/air:v1.61.0
    container_name: shop-api
    working_dir: /go/src/github.com/tamaco489/opensearch_demo/api/shop
    volumes:
      - ./shop:/go/src/github.com/tamaco489/opensearch_demo/api/shop
      - ~/.cache/go-build:/root/.cache/go-build
    ports:
      - "8080:8080"
    env_file:
      - ./shop/.env
    networks:
      - sandbox

  opensearch:
    image: opensearchproject/opensearch:2.19.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    env_file:
      - ./shop/.env
    ulimits:
      memlock:
        soft: -1 # メモリロックを無制限に設定（ソフトおよびハード制限なし）
        hard: -1
      nofile:
        soft: 65536 # OpenSearchユーザーの最大オープンファイル数を設定（少なくとも65536に設定）
        hard: 65536
    volumes:
      - ./shop/docker/opensearch/data:/usr/share/opensearch/data
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - sandbox

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - sandbox

networks:
  sandbox:
